In [1]:
import numpy as np

In [3]:
#ndarray.shape
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)

(3, 3)


In [5]:
#reshaping
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
#ndarray.ndim
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [11]:
#numpy.itemsize
x=np.array([1,2,3,4,5], dtype=np.int8)
print(x)

[1 2 3 4 5]


In [12]:
print(x.itemsize)

1


In [13]:
x=np.array([1,2,3,4,5], dtype=np.float32)
print(x)

[1. 2. 3. 4. 5.]


In [14]:
print(x.itemsize)

4
